export const meta = {
  name: 'batch-showcase-sites',
  description: 'Build/resume a small batch of showcase sites through build(optional)+3 passes',
  phases: [
    { title: 'Build', detail: 'one builder agent per site (skipped in resume mode)' },
    { title: 'Pass 1 — Art Direction', detail: 'composition, hierarchy, type, color' },
    { title: 'Pass 2 — Motion & Interaction', detail: 'choreography, micro-interactions, wow moment' },
    { title: 'Pass 3 — Craft & Verify', detail: 'meta, a11y, perf, copy, final CLEAN check' },
  ],
}

const ROOT = ROOT
const BATCH_SLUGS = ['verse','hearth','gatsby','vapor']
const BATCH_MODE = 'build'

const BRIEFS = [
{num:'01',slug:'aurelia',brief:`AURELIA — an ethereal luxury perfume house. Mood: liquid light, silk, dawn. HERO: a full-viewport Three.js scene (importmap, three@0.160.0 from unpkg) — an iridescent silk-like surface (plane geometry displaced by layered simplex noise in a custom vertex shader, fragment shader doing thin-film iridescence that shifts with view angle), drifting slowly, reacting subtly to cursor. Palette: pearl #F6F2EC, champagne gold #C9A96A, deep ink #14121C, iridescent rose/teal shimmer accents. Fonts: Cormorant Garamond (display, large italic moments) + Outfit (body). Sections: hero with huge serif wordmark over the silk; three fragrance 'compositions' (Aube, Méridien, Minuit) as cards whose backgrounds are small canvas gradient loops in each scent's palette; an 'accords' section with animated layered translucent circles showing note pyramids; maison manifesto with generous whitespace; footer. Interactions: magnetic hover on nav links, slow parallax, scent cards tilt on hover with sheen sweep. Copy voice: hushed, precise, French-inflected luxury.`},
{num:'02',slug:'grotesk',brief:`GROTESK™ — a brutalist type foundry specimen site. Mood: loud, confident, anti-decoration. Palette: #0A0A0A, #FAFAFA, signal red #FF2D2D only. Fonts: Archivo Black (display) + Space Grotesk (body/mono moments); ALSO load a variable font (e.g. 'Anybody' wdth/wght) for the interactive specimen. Structure: massive viewport-filling headline that you can DRAG to warp (pointer position maps to variable-font wght/wdth axes live); a relentless marquee strip of glyphs; a specimen grid (A–Z displayed huge, each cell inverts on hover with a hard snap — no easing, brutalism means abrupt); a 'waterfall' section with the same sentence at 12 sizes; pricing table with harsh 4px borders; giant footer wordmark cropped by overflow. Kinetic type: headline letters stagger-slam in on load; scroll-velocity skews the marquee. Raw visible grid lines, black 8px borders, zero border-radius, underlines as 8px blocks. Copy: terse manifesto lines like 'TYPE IS INFRASTRUCTURE.'`},
{num:'03',slug:'strata',brief:`STRATA — a generative art gallery that mints a unique flow-field artwork every visit. Mood: dark gallery, warm spotlights. Palette: gallery black #0E0D0B, warm white #EFE9DD, brass plaque #A6854D; artwork palettes rotate from 4 curated sets (ember, glacier, moss, dusk). Fonts: Fraunces (display, soft wonk) + Inter (labels/plaques). Core: a large canvas 'painting' in an ornate-thin frame — particles advected through curl/flow-noise leaving strokes, seeded RNG (mulberry32) with seed shown on a brass plaque ('Edition No. 4821-C'); 'Re-mint' button regenerates with a new seed and a museum-style label update. Second room: a horizontal-scroll wall of 6 smaller pre-seeded canvases, each with plaque + palette name. Explain-the-algorithm section with an elegant animated diagram (vectors of the field drawn as tiny SVG arrows that reorient). Spotlight vignette lighting via radial gradients; cursor is a soft light that gently brightens what it passes. Copy: curatorial, plaque-style.`},
{num:'04',slug:'deepfield',brief:`DEEPFIELD STATION — retro CRT mission control for a deep-space telescope. Mood: 1978 console, phosphor glow. Palette: near-black #050805, phosphor green #33FF66, alert amber #FFB000; scanlines + slight barrel distortion vibe (CSS only: repeating-linear-gradient scanlines, vignette, subtle flicker animation, text-shadow bloom). Fonts: VT323 (everything terminal) + IBM Plex Mono (dense data). Structure: boot sequence on load (typewriter lines with checksums, cursor block blinking) → main console: live telemetry panel (numbers ticking: photon counts, gimbal angles, drift), an ASCII starfield map where a target reticle slowly slews, a command line where preset commands (HELP, SCAN, TARGET ANDROMEDA, DIAGNOSTICS) type out responses, an anomaly event that triggers amber alert mode after some seconds (palette shifts, klaxon banner). Everything monospace-grid aligned; blocky box-drawing borders (┌─┐). Copy: laconic NASA-transcript style. This one should feel ALIVE — constant gentle data motion for video.`},
{num:'05',slug:'ma',brief:`間 (MA) — a meditation on Japanese negative space; a fictional kyoto paper-and-ink studio. Mood: stillness, restraint, breath. Palette: washi #F5F1E8, sumi ink #1C1A17, vermillion seal #C73E2E (used ONCE per view, tiny). Fonts: Noto Serif JP (display + Japanese characters) + Zen Kaku Gothic New (latin body). Layout: radical whitespace — content occupies maybe 30% of any viewport; vertical writing-mode (writing-mode: vertical-rl) for Japanese headings; a hero where a single sumi-e brushstroke SVG draws itself (stroke-dashoffset, textured brush look via multiple offset strokes + blur), then the character 間 fades in; sections separated by huge empty space with a single small element each (a stone: irregular border-radius blob; a seasonal haiku that crossfades between 4 seasons with matching subtle tint shifts; an enso circle drawing on scroll-into-view). A hanko seal stamps onto the footer with a soft thunk animation. Interactions: everything slow (1200ms+), opacity/translate only. Copy: sparse, koan-like, bilingual JP/EN.`},
{num:'06',slug:'descent',brief:`DESCENT — a scroll-driven cinematic journey from ocean surface to hadal trench. Mood: awe, pressure, darkness closing in. Palette: continuous gradient over scroll from surface #9BD4E4 → twilight #1B3A5C → midnight #0A1428 → hadal #02030F; bioluminescent accents #7FFFD4, #FF7EB6. Fonts: Playfair Display (poetic depth markers) + Source Sans 3 (fact cards). Mechanic: page is ~8 viewport-heights; a fixed depth-meter HUD on the right ticks meters (0m → 10,935m) tied to scroll; background color + light rays fade as you sink; layered parallax particles (marine snow) drift upward at different speeds. Encounters at depths, each an SVG creature with idle animation + glow: jellyfish (400m, pulsing bell), anglerfish (1200m, lure flicker), gulper eel (3000m), dumbo octopus (5000m), and at the bottom — the Trieste bathyscaphe with a plaque. Each encounter: name, depth, one astonishing fact sliding in. Light rays (CSS conic gradients) only in first 2 viewports. Finale: near-total darkness, single line of text, then 'return to surface' button that smooth-scrolls up fast like ascent. Sound: none. Copy: hushed documentary.`},
{num:'07',slug:'chromatic',brief:`CHROMATIC.SYS — Y2K liquid-chrome revival for a fictional 'graphics driver for dreams'. Mood: 1999 rave flyer meets Apple 2001. Palette: chrome silvers (#E8E8F0→#9FA4B8 gradients), holographic sweeps (pink #FF71CE, cyan #01CDFE, lime #05FFA1) on deep #0B0B12. Fonts: Unbounded (display) + Manrope (body). Visuals: big liquid-chrome blobs — SVG paths with gooey filter (feGaussianBlur+feColorMatrix) morphing slowly; chrome TEXT via background-clip:text with animated metallic gradient + moving specular highlight; a holographic foil card (tilts to cursor, foil sheen follows via radial-gradient at pointer); Windows-98-style window frames containing 'driver specs' with marquee title bars but styled premium; a download button with aggressive chrome bevel that depresses. Background: slow-rotating conic holo sheen + starburst lens flares (CSS). Section: 'changelog' as terminal-meets-glossy list. Everything glossy, curved, wet. Copy: techno-mystic ('renders your subconscious at 240Hz').`},
{num:'08',slug:'meridian',brief:`MERIDIAN — a Swiss International-Style editorial magazine, issue 04: 'On Precision'. Mood: Müller-Brockmann, air, order. Palette: paper #F4F1EA, ink #111111, Swiss red #E63329 (structural accents only). Fonts: Inter Tight (all — the discipline IS the statement), with weights 300–900 doing hierarchy work; optional Spectral for one pull-quote spread. Layout: visible 12-column grid (toggleable with a 'grid' button that overlays the actual columns in red hairlines — a designer's easter egg); asymmetric spreads: huge issue numeral '04' cropped at viewport edge; feature list with hanging indices; an essay spread with drop cap, tight measure, baseline-aligned rules; a diagram page recreating a Brockmann-style concert poster with animated concentric arcs (SVG, rotating extremely slowly); colophon set in tiny caps with letter-spacing. Interactions: restrained — red underline slides on hover, arcs respond ±5° to scroll, grid toggle. Type IS the imagery: no illustrations beyond geometric plates. Copy: an actual sharp 250-word essay on precision in design (write it well).`},
{num:'09',slug:'corpus',brief:`CORPUS — a WebGL particle universe. Mood: cosmic, sublime, alive. Palette: void #060614; particle hues electric ice #7DF9FF, violet #B39DFF, pink #FF6EC7 (additive blending). Fonts: Syne (display, weird-wide) + IBM Plex Sans (UI). Core: Three.js Points system, 45,000 particles, custom shader material (size attenuation, soft round sprites via fragment discard, additive). Particles morph between 4 target formations on a timed loop AND via nav clicks: (1) torus knot, (2) spiral galaxy with arm noise, (3) 3D grid lattice, (4) the word 'CORPUS' (sample text from an offscreen canvas). Morphs ease with staggered per-particle delays (stored in attribute) so transitions ripple. Mouse acts as a gravity well (repel on press). Slow camera orbit; slight fog. UI: minimal — formation names as nav dots with labels, a headline that crossfades per formation, stats line (particle count, fps). Handle DPR cap at 2 and pause when tab hidden. This must run at 60fps — profile particle count down if needed but keep ≥30k.`},
{num:'10',slug:'verdant',brief:`VERDANT — a botanical atelier & seed archive. Mood: greenhouse morning, patient growth. Palette: cream #F7F4EC, moss #3E5C3A, deep pine #1E2D1F, terracotta #C67B4F, soft chartreuse accent #B9C46A. Fonts: EB Garamond (display, botanical-plate elegance) + Karla (labels). Signature: SVG vines that GROW along the page as you scroll — long curving paths (stroke-dashoffset driven by IntersectionObserver/scroll) sprouting leaves (scale from nodes) and occasional blooms (petals unfurl via staggered rotate/scale from center). Sections: hero with a large botanical illustration built from layered SVG strokes drawing in; a seed catalog — cards styled as vintage seed packets (borders, stamps, latin names) that flip on hover; a 'growth calendar' as an elegant radial season wheel (SVG) with a slowly sweeping hand; a pressed-herbarium section where specimens (detailed SVG plants) sit on paper with tape corners and handwritten-style annotations (use an italic). Ambient: floating pollen motes, occasional leaf falling. Copy: field-journal warmth, latin binomials.`},
{num:'11',slug:'kowloon',brief:`KOWLOON NIGHTS — a neon cyberpunk night-market street. Mood: rain on asphalt, humming signs, Wong Kar-wai glow. Palette: wet dark #07070F, neon pink #FF2E88, cyan #00E5FF, sign yellow #FFE33D, occasional CJK red. Fonts: Chakra Petch (display/UI) + Noto Sans JP (sign glyphs 麺 酒 電). Scene: an isometric street built in pure CSS 3D — building blocks (transformed divs) with lit windows (animated opacity grid), layered neon signs (text + SVG tubes with authentic flicker: one sign has a dying letter that buzzes erratically), hanging cables, a noodle-stall glow. Canvas rain: streaks falling at an angle + splash flickers; puddle reflections as blurred inverted gradients that shimmer. Steam wisps (blurred blobs rising) from vents. Slow ambient camera: the whole scene gently translates/parallaxes with cursor. Below the fold: 'directory' of stalls as neon menu cards that ignite (flicker on) on hover; a marquee LED ticker with market announcements. Everything loops for video. Copy: noir-poetic stall descriptions, bilingual accents.`},
{num:'12',slug:'fold',brief:`FOLD — a paper-craft pop-up storybook: 'The Smallest Mountain'. Mood: handmade, warm lamplight, childlike wonder. Palette: kraft #D9C7A7, cream #FBF6EA, coral #F2695C, teal #2E8C83, sunshine #F2B33D. Fonts: Baloo 2 (display, rounded) + Nunito (body). Craft language: every element looks cut from paper — layered box-shadows (2-3 stacked, hard, small offsets) for lift, clip-path torn/scalloped edges, visible 'fold' center creases (linear-gradient shading). Structure: a 5-scene story told in full-viewport 'spreads'; on scroll-into-view each spread POPS UP — elements rotate up from the page fold (transform-origin bottom, rotateX from 90° to 0 with overshoot ease, staggered). Scenes: (1) valley with layered hill cutouts + paper sun on a stick that rotates, (2) the tiny mountain meets a cloud (cloud bobs on a visible paper tab), (3) night — dark blue overlay sheet with punched-hole stars (radial gradients) and a crescent, (4) spring pop-up with paper flowers unfurling, (5) end plate with 'The End' banner on strings that sways. Dangling elements swing on hover. A page-corner curl in the bottom-right advances scenes on click too. Copy: a genuinely charming 10-sentence story.`},
{num:'13',slug:'oscillate',brief:`OSCILLATE — a playable web synthesizer. Mood: 1984 polysynth meets Miami dusk. Palette: deep #0D0221, sunset grid horizon, neon gradient #FF3CAC→#784BA0→#2B86C5, key accents mint #00F0B5. Fonts: Michroma (display/faceplate) + Space Mono (labels/values). Instrument (WebAudio, all synthesized): 1.5-octave on-screen keyboard playable by click/touch AND computer keys (A W S E D F T G Y H U J K), voice = 2 detuned oscillators → lowpass filter → delay; controls as skeuomorphic-minimal knobs (drag vertically to turn; SVG with indicator line + value readout): cutoff, resonance, detune, delay mix; waveform selector (saw/square/tri) as glowing segmented switch; an arpeggiator toggle with rate knob that plays a preset pattern so the site demos itself; visualizers: oscilloscope (canvas, analyser waveform) as the hero backdrop line + a spectrum bar field at the bottom that doubles as decorative equalizer. Faceplate design: brushed-dark panel, screws in corners, silkscreen labels, a sunset-grid animated horizon behind. Keys light up when played (also when arp plays them). AudioContext resumes on first gesture; show a tasteful 'power on' switch that flips with a click, boots the panel LEDs sequentially. Copy: spec-sheet cool.`},
{num:'14',slug:'noir',brief:`NOIR — a monochrome luxury fashion house, collection 'Absence'. Mood: severe elegance, gallery silence. Palette: #0A0A0A and #F5F5F3 ONLY (grays via opacity). Fonts: Bodoni Moda (display, razor contrast, huge) + Figtree (whisper-small body). No photographs: garments suggested via elegant CSS/SVG silhouettes — flowing gradient forms with grain (SVG turbulence overlay), abstract but evocative. Layout: dramatic scale contrast — 20vw display type against 11px captions; a lookbook as horizontal scroll (scroll-snap) of numbered 'looks', each a silhouette + caption + look number in huge outlined type; hover reveals: headlines are outlined (webkit-text-stroke) and FILL on hover via clip-path wipe; a manifesto section set in a single narrow column, justified, with the word 'absence' pulled out at 8x size; hairline rules (0.5px) structuring everything; page number footer like a printed catalog. Interactions: cursor becomes a small crosshair; links invert a precise rectangle behind themselves; lookbook items sharpen from blur(2px) as they center. Motion: austere — nothing bounces; everything glides (cubic-bezier(0.16,1,0.3,1), 900ms). Copy: fashion-poetic, 5 words where 20 would be used.`},
{num:'15',slug:'almanac',brief:`ALMANAC — an astronomical data-observatory where charts are the art. Mood: 19th-century atlas meets modern data-viz. Palette: midnight #0B1026, star-paper #E8E4D8, celestial gold #D9A441, nebula teal #3E8989, mars #C2543A. Fonts: Newsreader (display + chart annotations, engraved feel) + IBM Plex Mono (data). All charts hand-drawn SVG/canvas, animated on scroll-into-view, real data: (1) hero — an orrery: concentric orbit rings with 6 planets actually revolving at relative speeds (Mercury visibly fast), labels in small caps, gold on midnight; (2) 'the brightness of stars' — a horizon-arc scatter of the 20 brightest stars, magnitude→size, twinkling subtly, hover shows name+distance in an elegant tooltip; (3) 'moons of the giants' — a horizontal comparative dot-strip (Jupiter 95, Saturn 146...) where dots pour in counted by a ticking numeral; (4) an eclipse timeline band 2026–2040 with type-set entries and a sweeping 'now' hairline; (5) a large annotated diagram of light travel time (concentric time rings: Moon 1.3s → Sun 8m20s → Neptune 4h) with a photon pulse animating outward on loop. Engraved-atlas details: fine double-rule borders, corner rosettes, figure numbers ('Fig. IV'), footnote asterisks. Copy: wonder with precision.`},
{num:'16',slug:'bauhaus',brief:`BAUHAUS SPIELPLATZ — a Bauhaus playground where composition is interactive. Mood: 1923 Weimar poster come alive. Palette: canvas #F2E8DC, red #D93829, blue #2350A8, yellow #F2B705, black #141414. Fonts: Jost (everything — it IS the Futura homage; weights + all-caps + tracking do the work). Hero: a Kandinsky-esque composition of circles, triangles, rectangles, arcs and rules — each element DRAGGABLE with hand-rolled verlet-ish physics (velocity, friction, elastic boundary bounce); elements cast flat offset shadows; a 'RESET KOMPOSITION' stamp-button snaps everything back with springy stagger; a 'ZUFALL' (random) button re-scatters into a new generated-but-balanced composition. Sections: a manifesto band with huge rotated type on a red diagonal; 'form follows function' demonstrated by three toggle cards (circle/square/triangle) that each animate their 'function' (wheel rolls, window opens, arrow points); a poster gallery — 3 generated posters (SVG compositions with date/venue type) that regenerate on click; footer as classic diagonal-type poster block. Interactions: precise, geometric, snappy (200ms, ease-out). Copy: German-accented section titles with EN body, era-appropriate voice.`},
{num:'17',slug:'reverie',brief:`REVERIE — a dreamcore hotel that exists only while you sleep. Mood: soft surrealism, Magritte pastel fog, gentle uncanny. Palette: fog lavender #E8DFF5, blush #FDE2E4, powder sky #CDE7F0, twilight deep #2A2440 (for text + the night section), moon cream #FFF8E7. Fonts: Italiana (display, thin surreal elegance) + Mulish (body). Scenery (all CSS/SVG): drifting volumetric clouds (layered blurred ellipses moving at different speeds, some IN FRONT of content); a hero with a floating doorframe (CSS 3D, slowly rotating ±8°, casting an impossible shadow) standing on nothing, with stars visible THROUGH the door but pastel sky around it; a giant moon that follows scroll velocity slightly; floating objects with slow bob animations (a key, a chair, an umbrella — elegant SVG line-art) each with a soft shadow that detaches (shadow drifts separately — subtle wrongness); an Escher-nod staircase (SVG isometric) where a small orb endlessly descends (looped path animation). Sections: 'rooms' — cards for Room 000 (the room of forgotten names), Room π, Room Yesterday, each with a one-line surreal amenity list; check-in form that asks 'How long have you been asleep?' with a dial. Motion: everything 3-6s loops, sine easing, nothing ever fully still. Copy: gentle surrealism, second person.`},
{num:'18',slug:'verse',brief:`VERSE — kinetic poetry; words with physics. Mood: literary, ivory paper, ink that misbehaves. Palette: ivory #FBF8F1, ink #17151F, gold leaf #B8963E (rare). Fonts: Crimson Pro (poems) + Work Sans (UI whispers). Four short poems (write ORIGINAL good ones, 4-6 lines each), each with its own physics behavior, presented as full-viewport movements with a numbered index: (I) 'Gravity' — words hang in place; click any word and it FALLS (hand-rolled gravity + floor bounce + settle), knocking others; a 'lift' link floats them back with slow buoyancy; (II) 'Magnet' — letters subtly repel from the cursor within a radius (smooth spring return), so reading physically parts the text; (III) 'Assembly' — the poem starts as scattered drifting letters that, on scroll-into-view, glide home into place (FLIP-style, staggered by distance); (IV) 'Erosion' — as you read (scroll), earlier lines slowly lose letters (they drift off like ash) until only key words remain — the poem edits itself to its essence. Each movement has a small engraved numeral and title. Physics must feel PHYSICAL: velocity, easing, mass variance by word length. Reduced-motion: poems render static. Copy: the poems are the content — make them genuinely good, thematically about impermanence.`},
{num:'19',slug:'hearth',brief:`HEARTH — an explorable isometric village with a living day–night cycle. Mood: cozy, storybook, gentle. Palette DAY: sage #A8BFA0, cream #F6EFDF, ochre #D9A05B, slate roofs #6E7B8B, sky #CDE3EA; NIGHT: deep indigo sky #1B2440, warm window glow #FFC978, moonlit surfaces (desaturated cool versions). Fonts: Fredoka (display, rounded warmth) + Quicksand (body). The village: built from CSS 3D isometric blocks (transform: rotateX(60deg) rotateZ(-45deg) scene) — 6-8 buildings (bakery, observatory with dome, tiny library, cottages), trees (stacked cones), a windmill with rotating blades, a stream (animated gradient), lanterns. A big sun/moon toggle (a beautiful switch: sun slides down, moon rises, sky gradient + ALL building colors transition over 2s, windows light up one by one with slight random delays, fireflies appear (drifting glow dots), smoke starts from chimneys (rising blurred puffs), crickets… no audio — visual only). Hover any building: it gently lifts + a name tag appears ('The Flour & Ember Bakery — opens at dawn'). Below: 'village registry' cards with tiny isometric icon per building. Ambient always: windmill turns, stream flows, smoke drifts, birds (day) / fireflies (night). Copy: warm storybook narrator.`},
{num:'20',slug:'gatsby',brief:`THE GATSBY GRAND — an art-deco hotel, est. 1928. Mood: champagne evening, brass and velvet. Palette: deep emerald #0E1A16, gold #C9A227, champagne #F3E3C3, noir accents #0B0B0B. Fonts: Marcellus (display, deco caps) + Lora (body). Signature: SVG deco line-work that DRAWS ITSELF — sunburst fans, stepped chevrons, symmetric frame corners animate stroke-dashoffset as sections enter; a grand hero: symmetric deco frame around the hotel name, gold foil text with a slow specular sheen sweep (background-clip gradient animation), tiny champagne bubbles rising in the background (canvas, sparse, elegant). Sections: 'The Suites' — three cards (The Fitzgerald, The Meridian, The Aurora) with deco-corner frames, each revealing a room 'illustration' made of gold line-art on emerald when hovered (lines draw in); 'The Ballroom' — a centerpiece chandelier built from SVG gold arcs/drops that gently sway with sparkle glints; an elevator-style floor indicator as fixed side-nav (deco needle rotates to the section as you scroll, with floor numbers L, 2, 3, P); dinner menu set in exquisite centered type with gold rules and diamond glyph separators. Motion: stately, 600-900ms, velvet easing. Copy: 1920s grand-hotel voice, slightly theatrical.`},
{num:'21',slug:'vapor',brief:`VAPOR — a glassmorphic planetary weather console for a fictional exoplanet ('Kepler-1649c relay'). Mood: pristine sci-fi instrument, serene. Palette: base twilight indigo #1A1B3A→#2E2E5C gradient; per-weather accent shifts: rain (steel blue #6FA8DC), snow (ice #CFE6F5), aurora (teal/violet #48E5C2/#9D6FF0), heat (ember #F0885C). Fonts: Sora (display/readouts) + Albert Sans (body). Core: a full-bleed canvas weather simulation behind frosted-glass UI panels (backdrop-filter: blur+saturate, 1px white/10 borders, soft inner glow): FOUR weather modes switchable by an elegant segmented dial — RAIN (angled streaks, splashes, occasional lightning flash that lights the whole scene), SNOW (drifting flakes with depth layers + accumulation line), AURORA (flowing ribbon curtains via layered sine-wave gradients on canvas, stars), HEAT (rising shimmer distortion + ember motes + heat-haze bands). Panels: current conditions (big temp numeral that counts to new value on mode switch, condition glyph animated), a 7-'sol' forecast strip with mini animated icons, atmospheric composition donut (animated), wind field mini-map with flowing arrows. Mode switch morphs EVERYTHING (accent colors, panel tints, data values) over 1.2s. Copy: mission-console concise.`},
{num:'22',slug:'riot',brief:`RIOT PRESS — an anti-design punk zine collective, issue 'NOISE 013'. Mood: photocopier fumes, glorious chaos with secret discipline. Palette: newsprint #EFEFE6, xerox black #0D0D0D, toxic lime #B6FF00, shock pink #FF00A8; halftone dots everywhere (radial-gradient patterns). Fonts: Bungee (display) + Archivo (dense body) + a stamped/stencil moment via Rubik Mono One. Language: collage — headlines as cut-out ransom letters (each letter its own span with different bg/rotation/font-size); stickers ('AS SEEN ON NO TV', '100% UNCALIBRATED') rotated and layered with hard shadows, one peeling on hover; tape strips holding 'photos' (CSS-art halftone abstracts) at angles; a relentless marquee ticker top AND bottom with zine slogans; cursor drags a spray-paint trail (canvas, lime, fades); barcode + 'PRICE: 1 SAFETY PIN' details; a tilted table of contents where rows straighten violently on hover; 'MANIFESTO' section: massive text with random words highlighted pink/struck through, edited-by-hand vibe (scribble underlines via SVG). Everything slightly rotated (0.5-3°) BUT on an underlying grid — chaos with craft. An 'issue 013' page-flip counter that flickers. Copy: funny, sharp, anti-corporate.`},
{num:'23',slug:'stillness',brief:`STILLNESS — a breathing meditation instrument. Mood: dawn air, weightless calm. Palette: living gradients that DRIFT over minutes through curated sets: dawn (#F6E7D8→#D9C1E8), sea (#CFE8E0→#7FB5A6→deep), dusk (#E8C1B0→#8E7CC3→#2E2A4F); text ink adapts for contrast. Fonts: Source Serif 4 (display, humanist calm) + Nunito Sans (UI). Core: full-viewport raw WebGL (no library) fragment-shader gradient — layered simplex/fbm noise blending 3-4 palette colors, ultra-slow, grain overlay to prevent banding; palette cross-fades every ~40s or on set-selection. Breathing guide: a luminous ring at center that expands (INHALE 4s), holds (HOLD 7s, ring shimmer-pulses faintly), contracts (EXHALE 8s) — 4-7-8 pattern with the words fading in/out in sync and a thin progress arc; a session picker (1 / 3 / 5 minutes) and a breath counter in whisper-small type; completion moment: the ring dissolves into drifting particles and a single line appears ('you were here the whole time'). Optional soft chime on phase change (WebAudio synthesized bell, OFF by default, elegant toggle). The typography stays minimal — this site is about the shader + choreography being flawless. Handle reduced-motion with a static gradient + text-only guide.`},
{num:'24',slug:'relic',brief:`RELIC — the Museum of Vanished Sounds. Mood: dark museum hall, reverent, a little melancholy. Palette: exhibition dark #121110, bone label #E5DFD3, brass #B08D57, deep oxblood accent #6E2B25. Fonts: Prata (display, museum serif) + Assistant (labels). Concept: exhibits of sounds that no longer exist in daily life, each RECONSTRUCTED live via WebAudio synthesis (no samples!): (1) rotary-phone dial (filtered noise clicks in decelerating pattern), (2) typewriter + carriage-return bell, (3) dial-up modem handshake (the full chirp choreography — oscillator sweeps + noise bursts, abridged 6s), (4) cathode-TV degauss THUNK+hum, (5) film projector flutter, (6) telegraph morse ('SOS'). Presentation: a horizontal gallery of spotlit plinths (scroll-snap rooms) — each exhibit is an elegant SVG artifact line-illustration on a plinth under a volumetric spotlight cone (CSS gradient), with a museum placard (accession number, dates 'in service 1892–1985', description) and a brass 'LISTEN' button that plays the reconstruction while a canvas waveform visualizes it and the artifact subtly reacts (dial rotates, keys press). Spotlights bloom as each room centers. Entrance hall: museum title wall + floor-plan strip nav. Exit through the gift shop: postcards of the artifacts (hover-tilt cards). Copy: curatorial with quiet wit.`},
{num:'25',slug:'machina',brief:`MACHINA — an infinite-zoom voyage into the Mandelbrot set, 'powers of ten' style. Mood: mathematical sublime, instrument-grade. Palette: void #05060A, computation cyan #59F2E8, deep-zoom magma set (#1B0F2E→#7A2E8F→#F2A03D→#F7E8C8) for the fractal coloring, HUD gray-green #9FB3A8. Fonts: Share Tech Mono (HUD) + Exo 2 (narrative). Core: canvas Mandelbrot renderer (hand-written, smooth/continuous coloring, progressive refinement — render coarse then sharpen; typed arrays; keep it performant) executing a PRE-PLANNED cinematic zoom path: auto-plays a slow continuous dive (~2 orders of magnitude per 20s) through 5 chosen waypoints (seahorse valley → spiral arm → minibrot...), each waypoint triggering a narrative overlay card ('×10² — the coastline principle…') with coordinates; HUD frame: corner brackets, live readouts (center coords to 12 decimals ticking, zoom exponent, iteration count, render ms), a zoom-depth rail on the left with waypoint ticks lighting up. Controls: pause/resume dive, click-to-recenter (smoothly retargets), palette cycle button (3 curated colorings). Guard precision: cap zoom before float64 breakdown (~1e13) then elegantly loop back to start ('return to sea level' pull-back animation, fast reverse zoom). The math must be correct and the pacing meditative-cinematic. Copy: awe with rigor, Eames-documentary tone.`},
]

const CONSTRAINTS = `
HARD CONSTRAINTS
- Site root: ${ROOT}/public/{NN}-{slug}/ — main page at index.html; you may split css/js into local files in that directory. A guide page MUST exist at guide/index.html (i.e. /{NN}-{slug}/guide/).
- 100% hand-coded visuals: NO external images, NO stock, NO base64 photo blobs. Allowed external resources ONLY: Google Fonts (fonts.googleapis.com/fonts.gstatic.com) and three.js pinned via importmap to https://unpkg.com/three@0.160.0/build/three.module.js (+ /examples/jsm/ if needed). Nothing else. No other libraries — physics, easing, noise, audio: hand-roll them.
- Every page: proper <title>, meta description, og:title/og:description, inline SVG favicon (data URI), lang attr, charset, viewport meta.
- Footer (styled to match the site): "NN / 25 · <Site name> — designed & coded by Claude Fable 5" with links: "Index" → /  and "How it's made" → guide/ (relative link "guide/").
- The guide page: 300-600 words, styled IN THE SITE'S OWN aesthetic (not generic), explaining concept, the key techniques (name the actual APIs/tricks used), and the iteration-pass process. It shares the site's fonts/palette.
- PASSES.md in the site directory: append one dated section per pass describing what changed and why.
- No console errors. No alert(). Respect prefers-reduced-motion (media query: reduce → gentle/static fallbacks, site still legible & composed).
- Real copy ONLY - never lorem ipsum. Write sharp, in-voice copy. Short is fine; filler is not.
- Performance: cap devicePixelRatio at 2; use requestAnimationFrame; pause heavy loops on document.hidden; keep total local code reasonable (<400KB per site).
- Composed at BOTH 1440×900 and 390×844. Mobile isn't an afterthought: heavy scenes may simplify on small screens but must still look designed.
`

const RUBRIC = `
QUALITY RUBRIC (judge yourself against this, harshly)
1. Typography: characterful, tuned (clamp() scales, tracking, leading, optical sizes). Zero default-looking text.
2. Color: cohesive, intentional; text contrast ≥ 4.5:1 for body (artistic display text may flex but must stay readable).
3. Motion: choreographed & eased (custom cubic-beziers); CONTINUOUS ambient motion so a screen-recording looks alive at any moment; entrances staggered; nothing janky.
4. Depth & detail: layered backgrounds, texture/grain where fitting, micro-interactions, considered hover/focus states, custom cursor only where it serves the concept.
5. Craft: favicon, meta/og, no console errors, both viewports composed, focus-visible styles, reduced-motion path.
6. Voice: copy reads like a real brand with a point of view.
`

const SNAP = (nn, tag) => `
VISUAL VERIFICATION (mandatory)
Run: cd "${ROOT}" && node tools/snap.mjs /${nn}/ shots/${tag} 3500
(for heavy WebGL sites use 5000). Then use the Read tool to LOOK at shots/${tag}-desktop.png, shots/${tag}-desktop-late.png (animation state ~3s later) and shots/${tag}-mobile.png. Critique what you actually SEE, not what the code intends. If snap prints ISSUES, fix every one. The static server is already running on :4173 serving ${ROOT}/public.`

const SITE_META_SCHEMA = {
  type: 'object', additionalProperties: false,
  required: ['num','slug','title','tagline','accent','bg','fontDisplay','blurb'],
  properties: {
    num: {type:'string'}, slug: {type:'string'},
    title: {type:'string', description:'display name of the site'},
    tagline: {type:'string', description:'<= 8 words, in the site voice'},
    accent: {type:'string', description:'primary accent color hex'},
    bg: {type:'string', description:'dominant background color hex'},
    fontDisplay: {type:'string', description:'the display font family name used'},
    blurb: {type:'string', description:'one sentence (<=22 words) describing the site for the hub card'},
  },
}

function dirOf(b){ return `${b.num}-${b.slug}` }

const buildStage = (b) => agent(`You are an elite creative developer building site ${b.num} of a 25-site showcase demonstrating the outer limits of hand-coded web design. This will be screen-recorded for a very large audience. Your work must be portfolio-defining.

THE BRIEF
${b.brief}

${CONSTRAINTS}
${RUBRIC}

PROCESS
1. If "${ROOT}/public/${dirOf(b)}" already contains files, they are debris from an interrupted earlier attempt — delete the directory's contents and rebuild from scratch. Then: mkdir -p "${ROOT}/public/${dirOf(b)}/guide"
2. Build index.html (plus local css/js files if you prefer) fully realizing the brief. Aim high on the signature technique — it is the reason this site exists. Write real copy in the brand voice.
3. Build guide/index.html per the constraints.
4. Create PASSES.md with a "## Build — 2026-07-12" section (concept summary + what you implemented).
5. ${SNAP(dirOf(b), b.num + '-build')}
6. Fix everything broken or visibly unbalanced; re-snap until the page is composed on desktop AND mobile with zero console errors.

Return: 4-6 sentences — what you built, the signature technique, and any known weak spots for the next reviewer.`, {label:`build:${b.slug}`, phase:'Build'})

const resumeStub = (b) => `BUILD_ALREADY_COMPLETE. This site's build stage finished in an earlier session and produced a complete index.html (+ local css/js) plus PASSES.md documenting it. Before doing anything else: read ${ROOT}/public/${dirOf(b)}/PASSES.md and the current source files to understand what already exists.`

const passStage = (n, focus) => (prev, b) => agent(`You are iteration-pass ${n} of 3 on site ${b.num} ("${b.slug}") at ${ROOT}/public/${dirOf(b)}/ — a showcase site that must be world-class. You are a FRESH pair of expert eyes. The previous stage reported:
---
${typeof prev === 'string' ? prev : JSON.stringify(prev)}
---

ORIGINAL BRIEF (the site must still honor it):
${b.brief}

YOUR FOCUS THIS PASS: ${focus}

${CONSTRAINTS}
${RUBRIC}

PROCESS
1. ${SNAP(dirOf(b), `${b.num}-p${n}`)}
2. Read the current source files. Cross-examine screenshots against the rubric and your pass focus. List (to yourself) at least 5 concrete problems or elevation opportunities — then implement AT LEAST 4 of them. Real changes, not tweaks-for-show. If the signature technique underwhelms, make it richer.
3. Re-run snap with tag ${b.num}-p${n}v2 and LOOK again. Iterate until visibly better and zero console errors.
4. Append "## Pass ${n} — 2026-07-12" to PASSES.md: what you changed and why.
${n === 3 ? `5. FINAL GATE: verify rubric line-by-line; confirm footer links (Index → /, guide/), favicon, og tags, reduced-motion path, both viewports composed, snap CLEAN. The guide page must be excellent too — polish it.` : ''}

${n === 3
  ? 'Return the site metadata via structured output.'
  : 'Return: 4-6 sentences — what you improved, what you saw in the screenshots, and what still needs attention.'}`,
  n === 3
    ? {label:`pass3:${b.slug}`, phase:'Pass 3 — Craft & Verify', schema: SITE_META_SCHEMA}
    : {label:`pass${n}:${b.slug}`, phase:`Pass ${n} — ${n===1?'Art Direction':'Motion & Interaction'}`})

const slugs = BATCH_SLUGS
const mode = BATCH_MODE // 'build' | 'resume'
const batch = BRIEFS.filter(b => slugs.includes(b.slug))
if (batch.length !== slugs.length) {
  throw new Error(`slug mismatch: requested ${JSON.stringify(slugs)}, matched ${batch.map(b=>b.slug).join(',')}`)
}

log(`Batch (${mode}): ${batch.map(dirOf).join(', ')}`)

const stage0 = mode === 'build' ? buildStage : resumeStub

const results = await pipeline(
  batch,
  stage0,
  passStage(1, `ART DIRECTION. Composition & visual hierarchy, spacing rhythm (consistent scale), typographic tuning (sizes/weights/tracking/measure), color balance & contrast, section transitions, and anything that looks broken, empty, cheap, or template-like in the screenshots. Elevate the layout until it looks like an award-winning site, not a good codepen.`),
  passStage(2, `MOTION & INTERACTION. Choreography (staggered entrances, scroll-linked behavior), easing quality (no default 'ease'), CONTINUOUS ambient motion for video capture, micro-interactions (hover/press/focus), cursor treatment where fitting, and the signature WOW moment — if the site doesn't have one jaw-dropping beat yet, create it. Also fix mobile composition issues you see in the mobile screenshot.`),
  passStage(3, `CRAFT & FINISH. Meta/og/favicon/title, accessibility (contrast, focus-visible, aria labels on controls, reduced-motion), performance (DPR cap, rAF hygiene, paused-when-hidden), copy sharpening (kill filler, strengthen voice), guide-page quality, PASSES.md completeness, and final zero-error verification at both viewports.`)
)

const metas = results.filter(Boolean)
const failed = batch.filter((b, i) => !results[i]).map(b => dirOf(b))
if (failed.length) log(`INCOMPLETE (need retry): ${failed.join(', ')}`)
log(`Completed ${metas.length}/${batch.length} sites in this batch.`)
return { metas, failed }
