import { chromium } from 'playwright';
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 1440, height: 900 } });
await page.goto('http://localhost:4173/12-fold/', { waitUntil: 'networkidle' });
await page.waitForTimeout(400);
const s3 = await page.$('#s3');
await s3.scrollIntoViewIfNeeded();
await page.waitForTimeout(180);
await page.screenshot({ path: 'shots/12-mid-180.png' });
await page.waitForTimeout(220);
await page.screenshot({ path: 'shots/12-mid-400.png' });
await browser.close();
console.log('done');
