import { chromium } from 'playwright';
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 1440, height: 900 } });
const logs = [];
page.on('console', (m) => logs.push(`[${m.type()}] ${m.text()}`));
page.on('pageerror', (e) => logs.push(`[pageerror] ${e.message}`));
await page.goto('http://localhost:4173/12-fold/', { waitUntil: 'networkidle' });
await page.waitForTimeout(400);
await page.click('.curl');
await page.waitForTimeout(200);
await page.screenshot({ path: 'shots/12-curl-flip.png' });
await page.waitForTimeout(1200);
await page.screenshot({ path: 'shots/12-curl-after.png' });
console.log(JSON.stringify(logs));
await browser.close();
