import { chromium } from 'playwright';
const [, , sitePath, outPrefix] = process.argv;
const url = `http://localhost:4173${sitePath}`;
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 1440, height: 900 } });
await page.goto(url, { waitUntil: 'networkidle', timeout: 30000 });
await page.waitForTimeout(2000);
await page.screenshot({ path: `${outPrefix}-full-desktop.png`, fullPage: true });
await page.close();
const page2 = await browser.newPage({ viewport: { width: 390, height: 844 } });
await page2.goto(url, { waitUntil: 'networkidle', timeout: 30000 });
await page2.waitForTimeout(2000);
await page2.screenshot({ path: `${outPrefix}-full-mobile.png`, fullPage: true });
await page2.close();
await browser.close();
