import { chromium } from 'playwright';
const browser = await chromium.launch();
const ctx = await browser.newContext({ viewport: { width: 1440, height: 900 }, reducedMotion: 'reduce' });
const page = await ctx.newPage();
const errs = [];
page.on('console', m => { if (m.type() === 'error') errs.push(m.text()); });
page.on('pageerror', e => errs.push(e.message));
await page.goto('http://localhost:4173/14-noir/', { waitUntil: 'networkidle' });
await page.waitForTimeout(1500);
await page.screenshot({ path: 'shots/14-reduced-cover.png' });
await page.evaluate(() => document.getElementById('sec-lookbook').scrollIntoView());
await page.waitForTimeout(600);
await page.screenshot({ path: 'shots/14-reduced-lookbook.png' });
await page.evaluate(() => document.getElementById('sec-manifesto').scrollIntoView());
await page.waitForTimeout(600);
await page.screenshot({ path: 'shots/14-reduced-manifesto.png' });
console.log('errors:', errs.length ? errs.join(' | ') : 'none');
await browser.close();
