import { chromium } from 'playwright';
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 1440, height: 900 } });
const issues = [];
page.on('console', (m) => { if (m.type()==='error'||m.type()==='warning') issues.push(`[console.${m.type()}] ${m.text()}`); });
page.on('pageerror', (e) => issues.push(`[pageerror] ${e.message}`));
await page.goto('http://localhost:4173/16-bauhaus/', { waitUntil: 'networkidle' });
await page.waitForTimeout(1000);
await page.evaluate(() => window.scrollTo(0, document.getElementById('manifest').offsetTop - 40));
await page.waitForTimeout(900);
await page.screenshot({ path: 'shots/16-p3-manifest.png' });
await page.evaluate(() => window.scrollTo(0, document.getElementById('form').offsetTop - 40));
await page.waitForTimeout(900);
await page.screenshot({ path: 'shots/16-p3-form.png' });
await page.evaluate(() => window.scrollTo(0, document.getElementById('plakate').offsetTop - 40));
await page.waitForTimeout(900);
await page.screenshot({ path: 'shots/16-p3-plakate.png' });
await page.evaluate(() => window.scrollTo(0, document.getElementById('foot').offsetTop - 40));
await page.waitForTimeout(900);
await page.screenshot({ path: 'shots/16-p3-footer.png' });
console.log('issues', issues);
await browser.close();
